### ISSUE TITLE
Links occasionally not working on discord bot

### ISSUE THREAD

**Issue by jetstream0** [mat-1/Repldex#104]

**Comment by mat-1** [comment]
Can you add an example?

**Comment by jetstream0** [comment]
![image](https://user-images.githubusercontent.com/49297268/106034611-f6a82c00-6087-11eb-9dfa-46d41ebfc1f4.png)
@mat-1

**Comment by mat-1** [comment]
This happens when people put hyperlinks incorrectly `[repl.it](repl.it)` vs `[repl.it](/entry/repl.it)` (with the latter being correct)
