### ISSUE TITLE
Store translations in the database rather than memory

### ISSUE THREAD

**Issue by mat-1** [mat-1/Repldex#13]
Entry translations should be stored in the database instead of memory, so they persist across restarts and because replit doesn't like using a lot of memory

**Comment by jetstream0** [comment]
Sure working on this

**Comment by jetstream0** [comment]
hmm @mat-1 
![image](https://user-images.githubusercontent.com/49297268/93535498-efb02680-f8fb-11ea-948a-d5a2c7513d63.png)
Can you make new database "translations"? (client["translations"]) according to [docs](https://motor.readthedocs.io/en/stable/api-asyncio/asyncio_motor_client.html) looks like someone needs to do it in mongodb.

**Comment by mat-1** [comment]
I think MongoDB automatically creates the collection when you reference it. By "invalid database name" they probably mean something with spaces.

**Comment by jetstream0** [comment]
alright then

**Comment by mat-1** [comment]
Created new branch to work on this: https://github.com/mat-1/ReplDex/tree/database-translations

**Comment by mat-1** [comment]
Btw the translations should be stored in the entries themselves and not in a separate collection

**Comment by jetstream0** [comment]
urg

**Comment by Codemonkey51** [comment]
> urg

Urg?

**Comment by leon332157** [comment]
Closed since translation was removed.
