### ISSUE TITLE
Compiled repldex

### ISSUE THREAD

**Issue by Codemonkey51** [mat-1/ReplDex#23]
Maybe instead of using python we could use a compiled lang such as go, this could be to increase speed, and make deploying easier (just download 1 binary and add a config file and poof you can auto run, and get a compiled version.

**Comment by Codemonkey51** [comment]
@mat-1 @minx28 @jetstream0 what do you think about this

**Comment by jetstream0** [comment]
I know zero Go though.... 
So it would take a while for me to be useful

**Comment by Codemonkey51** [comment]
> I know zero Go though....
> So it would take a while for me to be useful

go is not too hard to learn, and that was only a suggestion we could use a different lang if we go the compiled route

**Comment by mat-1** [comment]
The main reason ReplDex is slow is because I'm using a free plan for the database.

**Comment by Codemonkey51** [comment]
> The main reason ReplDex is slow is because I'm using a free plan for the database.

Compiled repldex is also for people who want to deploy it by themself, 1) it is easier to set up a compiled program to work in PATH, 2) they may host there own db on the computer so they want the bot to be faster, idk

**Comment by Codemonkey51** [comment]
Also 1 file is much easier to use then a bunch of files + folders, that if they get tampered with could break the whole thing

**Comment by jetstream0** [comment]
eh, I think as mat said if we make everything async it should be much faster.

**Comment by mat-1** [comment]
Pretty much everything is async right now, except for the translations (somewhat related to #13)

**Comment by Codemonkey51** [comment]
ok

**Comment by Codemonkey51** [comment]
This seems a bit far out, if ever so I'll close it for now
