### ISSUE TITLE
Setup screen.

### ISSUE THREAD

**Issue by Codemonkey51** [mat-1/ReplDex#28]
I think repldex could have a first time setup screen for the website, configuring settings and adding editors ofc this would rely on #22 (for repl.it at least) to allow editors and admins to be configured, this screen could also setup bot support (maybe we make repldex discord bot optional) 

This screen could also be reused in the admin panel to configure features.

I'll work on a mock-up design of this screen

**Comment by Codemonkey51** [comment]
@mat-1 how do you think this would/could work

**Comment by mat-1** [comment]
Tbh I don't think this would be useful, and if someone is forking ReplDex they're already gonna have access to the files anyways.

**Comment by Codemonkey51** [comment]
Well for #22 it is a bit harder to configure editors/admins, so we probably need a way to set the owner ID (in admin panel there will be a way to add editors + admins once #22 goes thru, and owner could also give add admin perms)

**Comment by Codemonkey51** [comment]
But we could have a tool to easily add users like python3 migrate.py add editor id or something like that

**Comment by Codemonkey51** [comment]
I am going to close this for now, as it seems other tools/ideas can replace it
