### ISSUE TITLE
Frontend Rework/Redesign (CSS)

### ISSUE THREAD

**Issue by IreTheKID** [mat-1/Repldex#66]
The ReplDex frontend (website) hasn't seen any changes in quite a while, and I think it could use a lot of updating & reworking. I'd be down to work on this, as I've gotten a lot better at CSS the past few months (I still use frameworks cuz I'm lazy) and have quite a few ideas for good changes to how users interact with entries on ReplDex, editor or not.

I also wanna ask if it's okay to work with a CSS framework or if the CSS should be custom. (I was thinking about using [Bulma](https://bulma.io), because, again, I'm lazy).

If you have suggestions feel free to let me know =P (I'll include an ss of a prototype later or smth)

**Comment by Codemonkey51** [comment]
@mat-1 is using frameworks ok?

**Comment by mat-1** [comment]
I don't really like frameworks since they're generally hard to customize, make the site look low-effort, have confusing class names, and make the site take longer to load.
However, you can take the parts of Bulma you want and stick them in the CSS if you want

**Comment by IreTheKID** [comment]
Well, Bulma's whole design philosophy addresses the issues that you just mentioned @mat-1 and it's actually really easy to customize components and stuff. But if it really bothers you, I'll guess I can take the parts I need from Bulma's main CSS files.

**Comment by jetstream0** [comment]
What's wrong with the current css? Not responsive?

**Comment by mat-1** [comment]
The current CSS isn't that bad in my opinion, and it is responsive.

**Comment by IreTheKID** [comment]
The current CSS is not bad, but it can be ✨ **better** ✨

**Comment by JDOG787** [comment]
Yes current css is fine, but if we do change pls dont use a framework. I can help if we do change it, but i dont think theres a need right now

**Comment by JDOG787** [comment]
I think we should work on fixing bugs and adding features then change css later if needed. But as I said the css looks good

**Comment by IreTheKID** [comment]
You guys have vision smh

**Comment by Codemonkey51** [comment]
> You guys have no vision at all smh

~~You have no dev role anymore smh~~

**Comment by IreTheKID** [comment]
@Codemonkey51 @mat-1 

Anyways, does the ReplDex DB store user PFPs? I kinda need those for a few ideas...

**Comment by Codemonkey51** [comment]
> @Codemonkey51 @mat-1
> 
> Anyways, does the ReplDex DB store user PFPs? I kinda need those for a few ideas...

Not right now... You can prob query them when needed with discord.py

**Comment by IreTheKID** [comment]
ugh, fine :|

**Comment by Codemonkey51** [comment]
> ugh, fine :|

Can you share the ideas?

**Comment by IreTheKID** [comment]
@Codemonkey51 I'll let you know in the Discord later, but here's what I have so far (kinda): [DexCSS](https://dexcss.irethekid.repl.co/)

**Comment by JDOG787** [comment]
@IreTheKID That doesnt look any better...

**Comment by JDOG787** [comment]
And PLEASE no frameworks

**Comment by IreTheKID** [comment]
Alright, alright I get it :|

**Comment by JDOG787** [comment]
So no css rework?

**Comment by IreTheKID** [comment]
I'm working on it rn :)

**Comment by JDOG787** [comment]
No :(

**Comment by JDOG787** [comment]
@mat-1 @jetstream0 Are we doing a redesign or no? If so I'd like to help with it, though I dont know that we need to do it.

**Comment by IreTheKID** [comment]
I can invite you to the Repl I have for the CSS rework if ya want @JDOG787

**Comment by IreTheKID** [comment]
Anyways, I have a draft PR (#72) where I'm working on this rn.

**Comment by JDOG787** [comment]
> I can invite you to the Repl I have for the CSS rework if ya want @JDOG787

Well its looks like we arent redoing css

**Comment by JDOG787** [comment]
Just improvements
