### ISSUE TITLE
Deleting is broken

### ISSUE THREAD

**Issue by mat-1** [mat-1/Repldex#67]
Clicking the delete button redirects to `https://repldex.com/delete?id=`, and clicking the cancel button does not cancel.

**Comment by jetstream0** [comment]
yeah

**Comment by jetstream0** [comment]
It was never meant to be merged into master (idk why it was), but I'll try and fix it....

**Comment by jetstream0** [comment]
https://github.com/mat-1/Repldex/pull/69 should fix... we'll see. Will close after confirmation

**Comment by jetstream0** [comment]
#69 Does fix, but seems like you guys don't want deletions anymore, in that case we should eliminate the broken deletions from master
I will still be maintaining the deletions branch however

**Comment by Codemonkey51** [comment]
> #69 Does fix, but seems like you guys don't want deletions anymore, in that case we should eliminate the broken deletions from master
> I will still be maintaining the deletions branch however

Maybe what could be done is making deletions toggleable in config.json, and then just keeping it off on repldex.com

**Comment by jetstream0** [comment]
#97

**Comment by leon332157** [comment]
Fixed in #69
