### ISSUE TITLE
Infinite Scrolling Broke

### ISSUE THREAD

**Issue by IreTheKID** [mat-1/Repldex#74]
Infinite scrolling doesn't work anymore, the index page caps at around 21 entries. I highly suspect that this is an issue with the API, as I can't retrieve more than 21 entries at a time, and pagination doesn't work either.

**Comment by Codemonkey51** [comment]
#73 fixes api

**Comment by Codemonkey51** [comment]
Wait it was merged

**Comment by jetstream0** [comment]
Yeah, it might not have updated on repl.it though...

**Comment by Codemonkey51** [comment]
I'll pull it now

**Comment by Codemonkey51** [comment]
Nope, there is a new error I think reverting the refactoring might be best

**Comment by IreTheKID** [comment]
It's definitely a new error, before #73 was merged, the API endpoints returned a `404` but now they return a `500`.

**Comment by jetstream0** [comment]
Will look into it

**Comment by IreTheKID** [comment]
@mat-1 @Codemonkey51 

Some more info:

The `api/entry/<name>` endpoint works just fine, and so does `api/entries/<sort>`. The problem is when you pass query parameters like `?page=0&limit=21` to the entries endpoint that you run into `500` Errors.
