### ISSUE TITLE
newentry, selfentry commands are not working

### ISSUE THREAD

**Issue by githubuser9022** [mat-1/Repldex#80]

**Comment by jetstream0** [comment]
Hmm.. I think newentry works

**Comment by jetstream0** [comment]
You can set a self entry but it does not show up when you do `^selfentry`

**Comment by IreTheKID** [comment]
These commands are working as intended, I just used them right now.

**Comment by jetstream0** [comment]
![image](https://user-images.githubusercontent.com/49297268/104066665-a4759880-51b6-11eb-945d-6c641a3cf1f7.png)
doesn;t look like it @IreTheKID

**Comment by githubuser9022** [comment]
hmms

**Comment by leon332157** [comment]
fixed with the latest version
