### ISSUE TITLE
Multi word queries for ^entry are broken

### ISSUE THREAD

**Issue by jetstream0** [mat-1/Repldex#82]
god damn

**Comment by IreTheKID** [comment]
@jetstream0 I've got a fix for it working :)

**Comment by jetstream0** [comment]
will take a look

**Comment by Codemonkey51** [comment]
> @jetstream0 I've got a fix for it working :)

Catch all kinda breaks it idk if that is fixed now tho @mat-1 ?

**Comment by jetstream0** [comment]
Wdym monkey?

**Comment by Codemonkey51** [comment]
> Wdym monkey?

The reason why ^request only had 3 args work is because it used *args, and that broke the arg parser bc it looks at all args the functions take

**Comment by Codemonkey51** [comment]
Mat may have fixed but idk cc: @mat-1 pls confirm

**Comment by jetstream0** [comment]
Don't think so, repldex still not working

**Comment by jetstream0** [comment]
also broken for multi word ^request (no response at all)

**Comment by leon332157** [comment]
fixed with the latest version.
